# Generated by Django 5.2.14 on 2026-05-24 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название бизнес элемента')),
            ],
            options={
                'verbose_name': 'Бизнес элемент',
                'verbose_name_plural': 'Бизнес элементы',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название роли')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
            },
        ),
        migrations.CreateModel(
            name='AccessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_read', models.BooleanField(default=False, verbose_name='Может читать')),
                ('can_create', models.BooleanField(default=False, verbose_name='Может создавать')),
                ('can_update', models.BooleanField(default=False, verbose_name='Может обновлять')),
                ('can_delete', models.BooleanField(default=False, verbose_name='Может удалять')),
                ('business_element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access.businesselement')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_rules', to='access.role')),
            ],
            options={
                'verbose_name': 'Доступ',
                'verbose_name_plural': 'Доступы',
                'constraints': [models.UniqueConstraint(fields=('role', 'business_element'), name='unique_role_business_element')],
            },
        ),
    ]
